# Quran Verse Mapping Configuration
# This file contains the authoritative mapping of Surah names to verse counts
# Source: Official Quran text verification
# Last Updated: 2025-08-18
# Maintained by: Islamic Advisory Board

verse_limits:
  # Arabic Surah names with verse counts
  "البقرة": 286
  "آل عمران": 200  
  "النساء": 176
  "المائدة": 120
  "الأنعام": 165
  "الأعراف": 206
  "الأنفال": 75
  "التوبة": 129
  "يونس": 109
  "هود": 123
  "يوسف": 111
  "الرعد": 43
  "إبراهيم": 52
  "الحجر": 99
  "النحل": 128
  "الإسراء": 111
  "الكهف": 110
  "مريم": 98
  "طه": 135
  "الأنبياء": 112
  "الحج": 78
  "المؤمنون": 118
  "النور": 64  # This is key - An-Nur has 64 verses, not 352!
  "الفرقان": 77
  "الشعراء": 227
  "النمل": 93
  "القصص": 88
  "العنكبوت": 69
  "الروم": 60
  "لقمان": 34
  "السجدة": 30
  "الأحزاب": 73
  "سبأ": 54
  "فاطر": 45
  "يس": 83
  "الصافات": 182
  "ص": 88
  "الزمر": 75
  "غافر": 85
  "فصلت": 54
  "الشورى": 53
  "الزخرف": 89
  "الدخان": 59
  "الجاثية": 37
  "الأحقاف": 35
  "محمد": 38
  "الفتح": 29
  "الحجرات": 18
  "ق": 45
  "الذاريات": 60
  "الطور": 49
  "النجم": 62
  "القمر": 55
  "الرحمن": 78
  "الواقعة": 96
  "الحديد": 29
  "المجادلة": 22
  "الحشر": 24
  "الممتحنة": 13
  "الصف": 14
  "الجمعة": 11
  "المنافقون": 11
  "التغابن": 18
  "الطلاق": 12
  "التحريم": 12
  "الملك": 30
  "القلم": 52
  "الحاقة": 52
  "المعارج": 44
  "نوح": 28
  "الجن": 28
  "المزمل": 20
  "المدثر": 56
  "القيامة": 40
  "الإنسان": 31
  "المرسلات": 50
  "النبأ": 40
  "النازعات": 46
  "عبس": 42
  "التكوير": 29
  "الانفطار": 19
  "المطففين": 36
  "الانشقاق": 25
  "البروج": 22
  "الطارق": 17
  "الأعلى": 19
  "الغاشية": 26
  "الفجر": 30
  "البلد": 20
  "الشمس": 15
  "الليل": 21
  "الضحى": 11
  "الشرح": 8
  "التين": 8
  "العلق": 19
  "القدر": 5
  "البينة": 8
  "الزلزلة": 8
  "العاديات": 11
  "القارعة": 11
  "التكاثر": 8
  "العصر": 3
  "الهمزة": 9
  "الفيل": 5
  "قريش": 4
  "الماعون": 7
  "الكوثر": 3
  "الكافرون": 6
  "النصر": 3
  "المسد": 5
  "الإخلاص": 4
  "الفلق": 5
  "الناس": 6

# Alternative English names mapping to Arabic
english_to_arabic:
  "Al-Baqarah": "البقرة"
  "Al-Imran": "آل عمران"
  "An-Nisa": "النساء"
  "Al-Maidah": "المائدة"
  "Al-Anam": "الأنعام"
  "Al-Araf": "الأعراف"
  "Al-Anfal": "الأنفال"
  "At-Tawbah": "التوبة"
  "Yunus": "يونس"
  "Hud": "هود"
  "Yusuf": "يوسف"
  "Ar-Rad": "الرعد"
  "Ibrahim": "إبراهيم"
  "Al-Hijr": "الحجر"
  "An-Nahl": "النحل"
  "Al-Isra": "الإسراء"
  "Al-Kahf": "الكهف"
  "Maryam": "مريم"
  "Ta-Ha": "طه"
  "Al-Anbiya": "الأنبياء"
  "Al-Hajj": "الحج"
  "Al-Muminun": "المؤمنون"
  "An-Nur": "النور"
  "Al-Furqan": "الفرقان"
  "Ash-Shuara": "الشعراء"
  "An-Naml": "النمل"
  "Al-Qasas": "القصص"
  "Al-Ankabut": "العنكبوت"
  "Ar-Rum": "الروم"
  "Luqman": "لقمان"
  "As-Sajdah": "السجدة"
  "Al-Ahzab": "الأحزاب"
  "Saba": "سبأ"
  "Fatir": "فاطر"
  "Ya-Sin": "يس"
  "As-Saffat": "الصافات"
  "Sad": "ص"
  "Az-Zumar": "الزمر"
  "Ghafir": "غافر"
  "Fussilat": "فصلت"
  "Ash-Shura": "الشورى"
  "Az-Zukhruf": "الزخرف"
  "Ad-Dukhan": "الدخان"
  "Al-Jathiya": "الجاثية"
  "Al-Ahqaf": "الأحقاف"
  "Muhammad": "محمد"
  "Al-Fath": "الفتح"
  "Al-Hujurat": "الحجرات"
  "Qaf": "ق"
  "Adh-Dhariyat": "الذاريات"
  "At-Tur": "الطور"
  "An-Najm": "النجم"
  "Al-Qamar": "القمر"
  "Ar-Rahman": "الرحمن"
  "Al-Waqiah": "الواقعة"
  "Al-Hadid": "الحديد"
  "Al-Mujadila": "المجادلة"
  "Al-Hashr": "الحشر"
  "Al-Mumtahanah": "الممتحنة"
  "As-Saff": "الصف"
  "Al-Jumuah": "الجمعة"
  "Al-Munafiqun": "المنافقون"
  "At-Taghabun": "التغابن"
  "At-Talaq": "الطلاق"
  "At-Tahrim": "التحريم"
  "Al-Mulk": "الملك"
  "Al-Qalam": "القلم"
  "Al-Haqqah": "الحاقة"
  "Al-Maarij": "المعارج"
  "Nuh": "نوح"
  "Al-Jinn": "الجن"
  "Al-Muzzammil": "المزمل"
  "Al-Muddaththir": "المدثر"
  "Al-Qiyamah": "القيامة"
  "Al-Insan": "الإنسان"
  "Al-Mursalat": "المرسلات"
  "An-Naba": "النبأ"
  "An-Naziat": "النازعات"
  "Abasa": "عبس"
  "At-Takwir": "التكوير"
  "Al-Infitar": "الانفطار"
  "Al-Mutaffifin": "المطففين"
  "Al-Inshiqaq": "الانشقاق"
  "Al-Buruj": "البروج"
  "At-Tariq": "الطارق"
  "Al-Ala": "الأعلى"
  "Al-Ghashiyah": "الغاشية"
  "Al-Fajr": "الفجر"
  "Al-Balad": "البلد"
  "Ash-Shams": "الشمس"
  "Al-Layl": "الليل"
  "Ad-Duha": "الضحى"
  "Ash-Sharh": "الشرح"
  "At-Tin": "التين"
  "Al-Alaq": "العلق"
  "Al-Qadr": "القدر"
  "Al-Bayyinah": "البينة"
  "Az-Zalzalah": "الزلزلة"
  "Al-Adiyat": "العاديات"
  "Al-Qariah": "القارعة"
  "At-Takathur": "التكاثر"
  "Al-Asr": "العصر"
  "Al-Humazah": "الهمزة"
  "Al-Fil": "الفيل"
  "Quraysh": "قريش"
  "Al-Maun": "الماعون"
  "Al-Kawthar": "الكوثر"
  "Al-Kafirun": "الكافرون"
  "An-Nasr": "النصر"
  "Al-Masad": "المسد"
  "Al-Ikhlas": "الإخلاص"
  "Al-Falaq": "الفلق"
  "An-Nas": "الناس"

# Special handling for descriptive verses (no numerical validation)
descriptive_references:
  - "الۤـمۤ"  # Alif Lam Mim
  - "الۤمۤص"  # Alif Lam Mim Sad
  - "الۤر"    # Alif Lam Ra
  - "المۤص"   # Alif Lam Mim Sad
  - "كهيعص"  # Kaf Ha Ya Ayn Sad
  - "طه"     # Ta Ha
  - "طسم"    # Ta Sin Mim
  - "طس"     # Ta Sin
  - "يس"     # Ya Sin
  - "ص"      # Sad
  - "حمۤ"     # Ha Mim
  - "عسقۤ"    # Ayn Sin Qaf
  - "ق"      # Qaf
  - "ن"      # Nun

# Validation settings
validation_config:
  strict_mode: true  # Strict validation of verse numbers
  allow_descriptive: true  # Allow descriptive references like الۤـمۤ
  default_fallback: "في القرآن الكريم"  # Safe fallback text
  log_validation_failures: true
  scholar_approval_required: true