version: '3.8'

services:
  # Backend service - Production optimized
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    container_name: moaen_backend_prod
    environment:
      - DEBUG=false
      - ENVIRONMENT=production
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
    networks:
      - moaen_network
    restart: always
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Frontend service - Production optimized
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    container_name: moaen_frontend_prod
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - moaen_network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Redis for caching (optional but recommended for production)
  redis:
    image: redis:7-alpine
    container_name: moaen_redis_prod
    networks:
      - moaen_network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
    command: redis-server --appendonly yes --maxmemory 100mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local

networks:
  moaen_network:
    driver: bridge