// Mock for @tanstack/react-query

const mockQueryClient = {
  clear: jest.fn(),
  getQueryData: jest.fn(),
  setQueryData: jest.fn(),
  invalidateQueries: jest.fn(),
  removeQueries: jest.fn(),
  cancelQueries: jest.fn(),
  fetchQuery: jest.fn(),
  prefetchQuery: jest.fn(),
  ensureQueryData: jest.fn(),
  setQueriesData: jest.fn(),
  refetchQueries: jest.fn(),
  resetQueries: jest.fn(),
  isFetching: jest.fn(),
  isMutating: jest.fn(),
  getDefaults: jest.fn(),
  setDefaults: jest.fn(),
  getMutationDefaults: jest.fn(),
  setMutationDefaults: jest.fn(),
  mount: jest.fn(),
  unmount: jest.fn(),
};

module.exports = {
  QueryClient: jest.fn(() => mockQueryClient),
  QueryClientProvider: ({ children }) => children,
  useQuery: jest.fn(() => ({
    data: undefined,
    error: null,
    isLoading: false,
    isError: false,
    isSuccess: true,
    refetch: jest.fn(),
  })),
  useMutation: jest.fn(() => ({
    mutate: jest.fn(),
    mutateAsync: jest.fn(),
    isLoading: false,
    isError: false,
    isSuccess: false,
    data: undefined,
    error: null,
    reset: jest.fn(),
  })),
  useQueryClient: jest.fn(() => mockQueryClient),
  useInfiniteQuery: jest.fn(() => ({
    data: { pages: [], pageParams: [] },
    error: null,
    isLoading: false,
    isError: false,
    isSuccess: true,
    fetchNextPage: jest.fn(),
    fetchPreviousPage: jest.fn(),
    hasNextPage: false,
    hasPreviousPage: false,
    isFetchingNextPage: false,
    isFetchingPreviousPage: false,
  })),
  useIsFetching: jest.fn(() => 0),
  useIsMutating: jest.fn(() => 0),
  useMutationState: jest.fn(() => []),
  useQueries: jest.fn(() => []),
  useSuspenseQuery: jest.fn(() => ({
    data: undefined,
    error: null,
    refetch: jest.fn(),
  })),
  useSuspenseInfiniteQuery: jest.fn(() => ({
    data: { pages: [], pageParams: [] },
    error: null,
    fetchNextPage: jest.fn(),
    fetchPreviousPage: jest.fn(),
    hasNextPage: false,
    hasPreviousPage: false,
    isFetchingNextPage: false,
    isFetchingPreviousPage: false,
  })),
  QueryCache: jest.fn(),
  MutationCache: jest.fn(),
  focusManager: {
    setEventListener: jest.fn(),
    setFocused: jest.fn(),
    isFocused: jest.fn(() => true),
  },
  onlineManager: {
    setEventListener: jest.fn(),
    setOnline: jest.fn(),
    isOnline: jest.fn(() => true),
  },
  notifyManager: {
    setBatchNotifyFunction: jest.fn(),
    setScheduler: jest.fn(),
    batchCalls: jest.fn((fn) => fn()),
  },
  hashQueryKey: jest.fn(),
  isServer: false,
};
